version: '3.8'

services:
#  check-froz-api:
#    container_name: check-froz-api
#    image: check-froz-api
#    build:
#      context: .
#      dockerfile: Dockerfile
#    env_file:
#      - .env
#    ports:
#      - "3000:3000"
#    volumes:
#      - ./src:/app/src
#    depends_on:
#      - check-froz-postgresql

  check-froz-postgresql:
    container_name: check-froz-postgresql
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file:
      - .env
    networks:
      - postgres-network
    volumes:
      - ./db-data/:/var/lib/postgresql/data/
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
networks:
  postgres-network:
    driver: bridge